### PR TITLE
Marking as obsoletes with rs-symon

### PR DESCRIPTION
**Pull request by thebwt**
And removing the migration stuff in %post

Also that message is pointless and not necessary.

Relates to issue #59

### CODE REVIEW

**Comment by tonyskapunk** [comment]
I think we want to use `Obsolete` rather than `Conflicts`, per fedora [conflicts doc](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-dependencies.html#RPM_Guide-Dependencies-conflicts) and [obsoletes docs](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-dependencies.html#RPM_Guide-Dependencies-obsoletes).

From the [fedora guide](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-advanced-packaging.html#id860373)

> *Obsoletes, where one package obsoletes capabilities provided by another, usually used when a package changes name and the new package obsoletes the old name

**Comment by tonyskapunk** [comment]
@thebwt what are your thoughts? with my comments above?

**Comment by thebwt** [comment]
@tonyskapunk I don't mind either way, the change is super simple ;). I'll build both commits (the one with conflicts and the one with obsoletes)

**Comment by tonyskapunk** [comment]
@thebwt  I'm in favor of  using `Obsoletes` can you squash the commit with only that change?

**Comment by thebwt** [comment]
Github can do that automatically now, see the drop down beside "Merge pull request"

**Comment by tonyskapunk** [comment]
@thebwt nice, there has been some comments in #59 the proposal is to have `Obsoletes` with a specific version of `rs-sysmon` and `Provides` `rs-sysmon`

Can you add both?

**Comment by tonyskapunk** [comment]
@thebwt can you do:
```bash
Obsoletes: rs-sysmon < 0.9.5-2
Provides: rs-sysmon = %{version}-%{release}
```
As pointed out in #59 ?

**Comment by thebwt** [comment]
Alright, have a look.

**Comment by tonyskapunk** [comment]
sweet, squashing and merging ;)

**Comment by thebwt** [comment]
giphy

**Pull request merged**
