### PR TITLE
Plugin support

### LINKED ISSUE #115: Fix inconsistency between BACKUP_ITEMS and USE_
Back in issue #94 when working on the documentation and configuration of the settings, it was clear that there is a inconsistency between the list of `BACKUP_ITEMS` and the `USE_` variables (https://github.com/rackerlabs/recap/issues/94#issuecomment-306840909), it's required to be more consistent on those settings, likely to deprecate the use of `BACKUP_ITEMS` or create it in a dynamic way based on the `USE_` variables.

### PR DESCRIPTION
**Pull request by tonyskapunk**
- Splitting out core functions out of the `recap` script
- Increasing logging
- Deprecating `BACKUP_ITEMS`, instead finding reports/logs dynamically.
- Adding plugin support
- Added plugin template and two plugin examples

Due to the amount of change:
  - I'm inclined in making this version **2.0.0** of `recap`
  - For code review I'm looking for @StafDehat, @jamrok to chime in, while there is a lot of changes mostly is moving code from main `recap` to multiple files.

---
Fix #115, #155 

cc: @LukeHandle

### CODE REVIEW

**Comment by LukeHandle** [comment]
Hey @StafDehat or @jamrok, did either of you have a chance to review this? I've pre-emptively written a first plugin over in https://github.com/tonyskapunk/recap/pull/2 which is all but ready for this PR 😄

**Comment by LukeHandle** [comment]
Hey @tonyskapunk, are you able to rebase and give someone a poke? ;) Would be a shame to lose the progress made here.

**Comment by tonyskapunk** [comment]
[1.4.0](https://github.com/rackerlabs/recap/releases/tag/1.4.0) has been released, yay!

I've made some work on the package building bits: [rpm](https://src.fedoraproject.org/rpms/recap/pull-request/1), [deb](https://github.com/raxpkg/recap/pull/3)

I'm working now on the rebase part, hopefully we can have the PR reviewed starting next week.

**Comment by tonyskapunk** [comment]
The commits in this PR have been rebased. Now the code can be reviewed, tested, etc. so we can have work on a new version.

@LukeHandle , @jamrok, @StafDehat any cycles to do code review?

**Comment by LukeHandle** [comment]
@tonyskapunk I'll aim to take a look at how this runs the "recap" plugin this coming week.

**Comment by tonyskapunk** [comment]
Tested this branch successfully on the following distros:
- centos 6
- centos 7
- debian 8
- debian 9
- ubuntu 14.04
- ubuntu 16.04
- ubuntu 18.04

I helped myself using the ansible playbook in the PR #166

**Pull request merged**
