### PR TITLE
Add recaptool man page.

### LINKED ISSUE #53: need manpage for recaptool
We have man pages for `recap` and `recaplog`, but not for `recaptool`.  Can someone familiar with that utility write one?

### PR DESCRIPTION
**Pull request by tonyskapunk**
Fix #53

### CODE REVIEW

**Comment by tonyskapunk** [comment]
Please hold on this one, there is an undocumented feature in the recaptool that is not in place on the man page, nor explicit in the help output of the tool, since I'd like to see PR #67 introduced first I can include both changes on this PR once that's merged.

**Comment by tonyskapunk** [comment]
Alright, I've fixed the `man` page for `recaptool` including an undocumented feature, which is now clearly displayed on the tool itself via #69

**Comment by tonyskapunk** [comment]
It has been a good time without any additional comment on this, I'm going to merge since is documentation.  It will need a change in the `spec` file and the `Makefile` to include `recaptool.8` as well, I'll take care of that in another PR.

**Comment by carlwgeorge** [comment]
Before adding it to the spec file, a new version should be tagged so that way `recaptool.8` is in the tarball.

**Comment by tonyskapunk** [comment]
Yeah, that's what I saw on the `spec` file, I was thinking in **not** bumping the version since there is no change in the code, just on the docs, if I don't bump the version I understand there will be no new package, what would be your suggestion in this case?

**Comment by tonyskapunk** [comment]
@carlwgeorge created #71, might be useless, but I wanted to ensure we update all the pieces required for this new man page.

**Comment by carlwgeorge** [comment]
Really comes down to two options.

1. Bump the version to get a new tarball with the man page included.
2. Copy the the man page to `util/packaging/rpm/` directory and list it as `Source1` in the spec file.

Option 1 is easy and simple.  We don't even have to rush it, and just wait to merge #71 when a new version is imminent.
Option 2 is messier, but certainly doable.  We would just have to remember to undo it when the next version happens.

**Comment by tonyskapunk** [comment]
Yeah I rather wait, as many other changes are in coming.

Thanks!

**Pull request merged**
