### PR TITLE
Record point-in-time CPU usage, instead of average since boot (issue …

### PR DESCRIPTION
**Pull request by piersc**
…#39)

### CODE REVIEW

**Comment by Beerey** [comment]
Looks good to me, ran without issues and the output was usable (if ugly).  @man-chung , @eljrax , do either of you want to test it before merging?

**Comment by thisSIDEofRANDOM** [comment]
Tested out on a few boxes tonight and working good. I did want to ask any reason we are sorting on 6 instead of 7?

**Comment by rakevinwr** [comment]
Tested it out tonight and worked pretty well. I did want to ask if you guys think we should change to sorting on 7 instead of 6. Seems like %CPU is the column we want to grab for this.

**Comment by piersc** [comment]
OK, it looks like the columns change between RHEL6 and 7 - %CPU is column 6 on RHEL6 and column 7 on RHEL7:

```
RHEL6:
09:38:37          PID    %usr %system  %guest    %CPU   CPU  Command

RHEL7:
09:40:27      UID       PID    %usr %system  %guest    %CPU   CPU  Command
```

**Comment by StafDehat** [comment]
On my system, the %CPU column is actually the 7th, but I noticed your sort is targeting the 6th.  Was that a typo/miscount, or are our systems behaving differently?  If we can't trust the output format of pidstat, we may want to use top instead.  You can use "-o -%CPU" to guarantee the last 10 lines contain the 10 highest-CPU processes, then just tail it out:
```
galapagos ~ # ( top -bn 1 | grep '%CPU'; top -bn 2 -o -%CPU -d 5 | tail -n 10 | tac )
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3139 ahoward   20   0 2717108 729720 124940 S   6.8  4.5  13:21.80 firefox
 2063 root      20   0  588116 200612 181284 S   5.4  1.2  25:07.01 Xorg
 3147 ahoward   20   0 3400248 1.600g  86952 S   2.4 10.4  29:01.92 thunderbird
 1184 root      20   0  991620  18548  13652 S   2.2  0.1   0:09.25 NetworkManager
 3041 ahoward   20   0 2021164  87924  63844 S   1.4  0.5   1:34.31 VidyoDesktop
 1149 message+  20   0   44232   4960   3380 S   1.4  0.0   0:05.56 dbus-daemon
 7173 ahoward   20   0   41968   3780   3080 S   1.2  0.0   0:10.91 top
 2817 ahoward   20   0 1137152  36368  26664 S   1.0  0.2   0:04.65 nm-applet
 1590 root      20   0   44296   7684   6684 S   0.6  0.0   0:01.61 wpa_supplicant
 7475 root      20   0   41800   3688   3128 R   0.4  0.0   0:00.05 top
galapagos ~ # 
```

**Comment by tonyskapunk** [comment]
I reviewed all the commits in this PR, there was another PR that was merged #57 that had support for EL6 and EL7, I don't see a reason to keep this still open, the reference of the code is current: https://github.com/rackerlabs/recap/blob/master/src/recap#L329-L348

**Pull request closed without merging**
