### PR TITLE
Cpuusage

### PR DESCRIPTION
**Pull request by lil-cain**

### CODE REVIEW

**Comment by lil-cain** [comment]
Rebased changes by @piersc in #48, and add version detection to work
around differences in pidstat output format between RHEL 6 & RHEL 7 as
pointed out by @rakevinwr. Closes #39 #48.

**Comment by Beerey** [comment]
Assuming this needs to be RHEL5 compatible, the sorted_versions list you're generating which uses `sort --version-sort` won't work - it was introduced with RHEL6 sort.  (minor) but also missing an 'e' in the comment.

**Comment by carlwgeorge** [comment]
This detects `version_strings` by using rpm.  That won't work if this is installed on a non-rpm distribution.

**Comment by lil-cain** [comment]
@carlwgeorge If I add similar code to do this with dpkg, wil this suffice? Or do we aim to support non rpm/deb distros?

**Comment by thebwt** [comment]
Sysstat -v should do this universally

**Comment by thebwt** [comment]
Okay I take it back, this isn't easy to get the version of...

**Comment by lil-cain** [comment]
Yeah - I tried looking for version flags before trying the rpm thing. I can add something similar to use dpkg to get version numbers, but if maybe we need to pull the data directly from /proc, which would be pretty horrible to have to do in shell…

**Comment by thebwt** [comment]
``sar -V
sysstat version 10.2.0```

That works on my 14.04 server, how about on rhelish systems?

**Comment by carlwgeorge** [comment]
This works (with sar or any of the other sysstat binaries):

```
$ pidstat -V 2>&1 | awk '{if(NR==1){print$NF}}'
9.0.4
```

**Comment by piersc** [comment]
@lil-cain could you change the version detection in this PR to @carlwgeorge 's method?

**Comment by lil-cain** [comment]
@piersc Done - does that look good to you? If so, I'll squash the commits together, and it should be good to merge?

**Comment by piersc** [comment]
Testing now

**Comment by piersc** [comment]
Looks good to me!

**Comment by lil-cain** [comment]
should be ready to merge :-)

**Comment by bhgraham** [comment]
There is a typo in the first line of the commit.  

> # print th top 10 processes (by cpu usage) to the resources file

**Comment by lil-cain** [comment]
fixed - good spot

**Comment by piersc** [comment]
Awesome, thanks, merged.

**Pull request merged**
